// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dal

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q              = new(Query)
	Comment        *comment
	UserFavorVideo *userFavorVideo
	UserInfo       *userInfo
	UserLogin      *userLogin
	UserRelation   *userRelation
	Video          *video
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Comment = &Q.Comment
	UserFavorVideo = &Q.UserFavorVideo
	UserInfo = &Q.UserInfo
	UserLogin = &Q.UserLogin
	UserRelation = &Q.UserRelation
	Video = &Q.Video
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:             db,
		Comment:        newComment(db, opts...),
		UserFavorVideo: newUserFavorVideo(db, opts...),
		UserInfo:       newUserInfo(db, opts...),
		UserLogin:      newUserLogin(db, opts...),
		UserRelation:   newUserRelation(db, opts...),
		Video:          newVideo(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Comment        comment
	UserFavorVideo userFavorVideo
	UserInfo       userInfo
	UserLogin      userLogin
	UserRelation   userRelation
	Video          video
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:             db,
		Comment:        q.Comment.clone(db),
		UserFavorVideo: q.UserFavorVideo.clone(db),
		UserInfo:       q.UserInfo.clone(db),
		UserLogin:      q.UserLogin.clone(db),
		UserRelation:   q.UserRelation.clone(db),
		Video:          q.Video.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:             db,
		Comment:        q.Comment.replaceDB(db),
		UserFavorVideo: q.UserFavorVideo.replaceDB(db),
		UserInfo:       q.UserInfo.replaceDB(db),
		UserLogin:      q.UserLogin.replaceDB(db),
		UserRelation:   q.UserRelation.replaceDB(db),
		Video:          q.Video.replaceDB(db),
	}
}

type queryCtx struct {
	Comment        *commentDo
	UserFavorVideo *userFavorVideoDo
	UserInfo       *userInfoDo
	UserLogin      *userLoginDo
	UserRelation   *userRelationDo
	Video          *videoDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Comment:        q.Comment.WithContext(ctx),
		UserFavorVideo: q.UserFavorVideo.WithContext(ctx),
		UserInfo:       q.UserInfo.WithContext(ctx),
		UserLogin:      q.UserLogin.WithContext(ctx),
		UserRelation:   q.UserRelation.WithContext(ctx),
		Video:          q.Video.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
