// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserFavorVideo = "user_favor_videos"

// UserFavorVideo mapped from table <user_favor_videos>
type UserFavorVideo struct {
	UserInfoID int64 `gorm:"column:user_info_id;primaryKey" json:"user_info_id"`
	VideoID    int64 `gorm:"column:video_id;primaryKey" json:"video_id"`
}

// TableName UserFavorVideo's table name
func (*UserFavorVideo) TableName() string {
	return TableNameUserFavorVideo
}
