// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserLogin = "user_logins"

// UserLogin mapped from table <user_logins>
type UserLogin struct {
	ID         int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserInfoID int64  `gorm:"column:user_info_id" json:"user_info_id"`
	Username   string `gorm:"column:username;primaryKey" json:"username"`
	Password   string `gorm:"column:password;not null" json:"password"`
}

// TableName UserLogin's table name
func (*UserLogin) TableName() string {
	return TableNameUserLogin
}
